### ISSUE TITLE
Smart Panel crashes after enabling media RPC

### ISSUE THREAD

**Issue by yigitsalar** [dead8309/Kizzy#255]
**Describe the bug**
Infinix stock app Smart Panel (com.transsion.smartpanel) gets crashed after enabling media RPC on Kizzy.
**To Reproduce**
1. Enter Kizzy
2. Tap to media RPC
3. Wait a while to get crash
4. See crash message sent by LogFox or any logcat/crash log app

**Expected behavior**
It mustn't crash
**Screenshots**
[Screenshot_20240302-180019](https://github.com/dead8309/Kizzy/assets/91019435/796fde07-0671-49ce-9677-0ff31e098b82)

**Please complete the following information:**
 - Device: Infinix NOTE 30 Pro 
 - OS: Android 13, XOS build X678B-H894OPQ-T-OP-231031V2861
 - Kizzy Version: 5.3

**Additional context**
Crash log by LogFox:
```
FATAL EXCEPTION: main
Process: com.transsion.smartpanel, PID: 24844
java.lang.RuntimeException: Could not copy bitmap to parcel blob.
	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2282)
	at android.graphics.drawable.Icon.writeToParcel(Icon.java:936)
	at android.app.Notification.writeToParcelImpl(Notification.java:3109)
	at android.app.Notification.writeToParcel(Notification.java:3042)
	at android.service.notification.StatusBarNotification.writeToParcel(StatusBarNotification.java:225)
	at android.os.Parcel.writeParcelable(Parcel.java:2548)
	at android.os.Parcel.writeValue(Parcel.java:2449)
	at android.os.Parcel.writeValue(Parcel.java:2326)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1275)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1344)
	at android.content.Intent.writeToParcel(Intent.java:11543)
	at android.os.Parcel.writeTypedObject(Parcel.java:2167)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6103)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:2029)
	at android.app.ContextImpl.startService(ContextImpl.java:1984)
	at android.content.ContextWrapper.startService(ContextWrapper.java:817)
	at com.transsion.smartpanel.NotificationListener.a(SourceFile:9)
	at com.transsion.smartpanel.NotificationListener.onNotificationPosted(SourceFile:2)
	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:450)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2311)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:204)
	at android.os.Looper.loop(Looper.java:291)
	at android.app.ActivityThread.main(ActivityThread.java:8133)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
```

**Comment by yegetshalaay** [comment]
It happens with app detection too, but not sure since I cannot able to obtain crash log.

**Comment by dead8309** [comment]
fixed in 9e1b28693d73ca4a648e4a2981da5af7004e478b
